1. select salesman.name, customer.name , slaesman.city, customer.city from salesman, customer where salesman.city = customer.city;
2. select order.order_no, order.purch_amt, customer.cust_name, customer.city from orders, customer where order.customer_id = customer.customer_id and customer.purch_amt between 500 and 2000;
3. select customer.cust_name, salesman.name from customer, salesman where customer.salesman_id = salesman.salesman_id;
4. select customer.customer_id, customer.cust_name, customer.city, customer.grade from customer join salesman on customer.salesman_id = salesman.salesman_id where  salesman.commission > 0.12;
5. select a.customer_id, a.cust_name, a.city, a.grade from customer a join salesman b on a.salesman_id = b.salesman_id where b.commission > 0.12 and a.city<>b.city;
6. select a.ord_no, a.ord_date, a.purch_amt, c.name, c.commission from orders a join customer b on a.customer_id = b.customer_id join slaesman c on b.salesman_id = c.salesman_id;
7. select * from orders natural join customers natural join salsesman;
8. select * from customer left join salesman on customer.salesman_id = salesman.salesman_id order by customer_id;
9. select * from customer left join salesman on customer.salesman_id = salesman.salesman_id where customer.grade < 300 order by customer_id;
10. select a.cust_name, a.city, b.ord_no, b.ord_date, b.pruch_amt from customer a left join orders b on a.customer_id = b.customer_id order by b.ord_date;
11. select a.cust_name, a.city, b.ord_no, b.ord_date, b.purch_amt, c.name, c.commission from customer a left join orders b on a.customer_id = b.customer_id left join b.salesman_id = c.salesman_id;
12. select * from salesman left join customer on salesman.salesman_id = customer.salesman_id;
13. select * from salesman right join customer on salesman.salesman_id = customer.salesman_id right join order on customer.customer_id = order.customer_id;
14. select * from salesman left outer join customer on salesman.salesman_id = customer.salesman_id left join orders on customer.customer_id = order.customer_id where order.purch_amt > 2000 and customer.grade is not null;
15. select customer.cust_name, customer.city, order.ord_no, order.ord_date, order.purch_amt from customer left join order on customer.customer_id = orders.customer_id;
16. select customer.cust_name, customer.city, order.ord_no, order.ord_date, order.purch_amt from customer full outer join order on customer.customer_id = orders.customer_id where customer.grade is not null;
17. select * from salesman cross join customer ;
18. select * from salesman cross join customer where customer.city is not null;
19. select * from salesman cross join customer where customer.grade is not null and salesman.city is not null;
20. select * from salesman cross join customer where salesman.city is not null and customer.grade is not null and salesman.city<>customer.city;
21. select * from item_mast join company_mast on item_mast.pro_com = company_mast.com_id;
22. select item_mast.pro_name, item_mast.pro_price, company_mast.com_name form item_mast join company_mast on item_mast.pro_com = company_mast.com_id;
23. select avg(item_mast.pro_price), company_mast.com_name from item_mast join company_mast on item_mast.pro_com = company_mast.com_id group by company_mast.com_name;
24. select company_mast.com_name from company_mast join item_mast on item_mast.pro_com = company_mast.com_id group by company_mast.com_name having avg(pro_price ) >= 350;
25. select company_mast.name, item_mast.pro_id, item_mast.price from company_mast join item_mast on company_mast.com_id = item_mast.pro_com having max(pro_price); 
26. select a.emp_idno, a.emp_fname, a.ema_lname, a.emp_dept, b.dpt_name from emp_details join emp_department on a.emp_dept = b.dpt_code;
27. select b.emp_fname, b.emp_lname, a.dpt_name, a.dpt_allotment from emp_details join emp_department on b.emp_dept = a.dpt_code ;
28. select emp_details.emp_fname, emp_details.emp_lname from emp_details join emp_department on emp_details.emp_dept = emp_department.dpt_code and emp_department.dpt_allotment > 50000;
29. select emp_department.dpt_name from emp_department join emp_details on emp_department.dpt_code = emp_details.emp_dept group by emp_department.dpt_name having count(*) > 2;
