1. select * from salesman;
2. select "This is SQL Exercise, Practice and Solution";
3. select 1, 2, 3;
4. select 10+15;
5. select 1+2*3;
6. select name, commission form salesmen;
7. select ord_date, salesman_id, ord_no, purch_amt from orders;
8. select distinct salesman_id from orders order by customer_id;
9. select name, city from salesman where city = "Paris";
10. select * from customer where grade = 200;
11. select order number, order date, purch_amt from orders where samesman_id = 5001;
12.select * from item_mast where pro_price between 200 and 600;
13. select avg(pro_price) from item_mast where pro_com = 16;
14.select pro_name, pro_price as Rs from item_mast ;
15.select pro_name, pro_price from item_mast where price >= 250 order by price  desc;
16. select avg(pro_price) from item_mast order by pro_com;
17. select pro_name, pro_price form item_mast where pro_price = (select min(pro_price) from item_mast);
18. select distinct emp_lname from emp_details;
19. select * from emp_details where emp_lname = 'Snares';
20. select * from emp_details  where emp_dept = 57;